from enum import StrEnum


class DreaminaErrorCategory(StrEnum):
    CLI_NOT_FOUND = "CLI_NOT_FOUND"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    CREDIT_INSUFFICIENT = "CREDIT_INSUFFICIENT"
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    MODEL_UNSUPPORTED = "MODEL_UNSUPPORTED"
    NETWORK_ERROR = "NETWORK_ERROR"
    TASK_FAILED = "TASK_FAILED"
    OUTPUT_PARSE_FAILED = "OUTPUT_PARSE_FAILED"
    UNKNOWN_CLI_ERROR = "UNKNOWN_CLI_ERROR"

